export * from './types'
export { makeRandom } from './random'
export type { Random } from './random'
export { alleleById, allelesAt, genotypeString, makeGenotype } from './genotype'
export { meiose } from './meiosis'
export { cross } from './cross'
export type { CrossOptions, Offspring } from './cross'
export { computePhenotype } from './phenotype'
export { computePunnett } from './punnett'
export type { PunnettRow } from './punnett'
